name: Deploy Staging Builds To Firebase

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS
### FIREBASE_TOKEN

on:
  push:
    branches:
      - develop
  workflow_dispatch:

defaults:
  run:
    working-directory: ios

jobs:
  lint:
    name: Run SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SwiftLint for files changed in the PR
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
        with:
          args: --strict

  deploy_ios_staging_to_firebase:
    name: Deploy iOS staging to Firebase
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Firebase-Tools
        run: |
          yarn global add firebase-tools
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Setup Google Services for Staging
        env:
          IOS_GOOGLE_SERVICE_INFO_STAGING: ${{ secrets.IOS_GOOGLE_SERVICE_INFO_STAGING }}
        run: |
          mkdir -p Surveys/Configurations/Plists/GoogleService/Staging
          touch Surveys/Configurations/Plists/GoogleService/Staging/GoogleService-Info.plist
          echo $IOS_GOOGLE_SERVICE_INFO_STAGING | base64 --decode > ./Surveys/Configurations/Plists/GoogleService/Staging/GoogleService-Info.plist

      - name: Setup Android Signing
        env:
          ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
          ANDROID_SIGNING_PROPERTIES: ${{ secrets.ANDROID_SIGNING_PROPERTIES }}
        run: |
          touch ../config/release.keystore
          echo $ANDROID_RELEASE_KEYSTORE | base64 --decode > ../config/release.keystore
          touch ../signing.properties
          echo $ANDROID_SIGNING_PROPERTIES | base64 --decode > ../signing.properties

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Generate KMM frameworks for Cocoapods
        run: |
          cd ..
          ./gradlew generateDummyFramework

      - name: Cache Bundler
        uses: actions/cache@v2
        id: bunlderCache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Bundle install
        run: bundle install

      - name: Cache Pods
        uses: actions/cache@v2
        id: cocoapodCache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Install Pods Dependencies
        run: bundle exec pod install

      - name: Match Ad-hoc
        run: bundle exec fastlane sync_adhoc_signing
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

      - name: Build App and Distribute to Firebase
        run: bundle exec fastlane build_and_upload_staging_app
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
