name: Deploy Production Builds To App Store

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS
### APPSTORE_CONNECT_API_KEY

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ios

jobs:
  build_and_upload_to_app_store:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Google Services for Production
        env:
          IOS_GOOGLE_SERVICE_INFO: ${{ secrets.IOS_GOOGLE_SERVICE_INFO }}
        run: |
          mkdir -p Surveys/Configurations/Plists/GoogleService/Production
          touch Surveys/Configurations/Plists/GoogleService/Production/GoogleService-Info.plist
          echo $IOS_GOOGLE_SERVICE_INFO | base64 --decode > ./Surveys/Configurations/Plists/GoogleService/Production/GoogleService-Info.plist

      - name: Setup Android Signing
        env:
          ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
          ANDROID_SIGNING_PROPERTIES: ${{ secrets.ANDROID_SIGNING_PROPERTIES }}
        run: |
          touch ../config/release.keystore
          echo $ANDROID_RELEASE_KEYSTORE | base64 --decode > ../config/release.keystore
          touch ../signing.properties
          echo $ANDROID_SIGNING_PROPERTIES | base64 --decode > ../signing.properties

      - name: Setup Konfig Properties
        env:
          KMM_KONFIG_PROPERTIES: ${{ secrets.KMM_KONFIG_PROPERTIES }}
        run: |
          touch ../buildKonfig.properties
          echo $KMM_KONFIG_PROPERTIES | base64 --decode > ../buildKonfig.properties

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Generate KMM frameworks for Cocoapods
        run: |
          cd ..
          ./gradlew generateDummyFramework

      - name: Cache Bunlder
        uses: actions/cache@v2
        id: bunlderCache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Bundle install
        run: bundle install

      - name: Cache Pods
        uses: actions/cache@v2
        id: cocoapodCache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Install Pods Dependencies
        run: bundle exec pod install

      - name: Match AppStore
        run: bundle exec fastlane sync_appstore_signing
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

      - name: Build App and Distribute to AppStore
        run: bundle exec fastlane build_and_upload_appstore_app
        env:
          APPSTORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
